sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
script:
- './gradlew clean build && if [ "$TRAVIS_BRANCH" == "master" ]; then ./gradlew bintrayUpload; fi'
env:
  global:
  - secure: IC6KusISt5uV3zmgf559BHfxBUqVl4OFv/qbFudlyD3rldVTnuPziG+f89WA1pp1youWd00gjIUGJ1AbULrqC7NN2PxtJivheTmNnfLad7PB4wUsIii2WQ9XnsUFKFqzOhEvY1JmdK221OXFYjVHFjpSRpB64irvUUnt2feMlox1iekOo1ZfFga1PXpcTmHYQSoStmWZnbwIU2ozSdg9IPrCwSh5fClwqdWfb96pcFsChE9kL3A7iw0PVsBmuFzSHqATnihkIOUxZR9IE1lge6Y380mlTZbQrtXy9nZaSndp57u8z5QOr9mtrY4LyMEYl5NiCfVsJqLLWqyU0DwUipg4tnBMEffiJjwhu4ZUDB4KCUZBe7kOfSOgKfvYPDyCkoqWM2HZ4P1mwwq5fpxtMtMvlj95PMDJ1Nmbt9hkSEuDJ67mZemYIBl8/rzF6iP5mmnPR4F+mq//QO2SR4QWEc/32WDG0vMRnFeNknj9TEG+72V4fm9dDm/lJy5H4eMKjCc0n9OethJstWD11Qc6f4qgwSDwPTT/VmHoqN46Nxw5UOArOYsyXNljbaxz7e8EcCWdKb0hYgwsMxjuy5dR0zaKyPt3VXYaH7f793gts+7jkQ4s/9ZcVT9S1Ocu5kb3GgSsfVQ5ei/c8ExSOrjx1N3YuprBPBHAdy1vobsyux8=
  - secure: IJEq2MgsCdSsxQQv8z7k0jlVKpapme0mmMsqa8GmTYWlhzm/tdJcFeOme1+Nbfl926YH6OmuusGaftrsyvfEZ20d2N90bCYmEXnTPILGDYC2S7QG6Y5MiKbKlrZ6BQgMejOi5YKitVhlz2vhGV855wHHtGj2yBgtJR2r05bMO9LJMbD8O+lo6/3us4fLBfXVcHUs6yAiJY6jKtvqZYwcBMIYutAgxwtbA6JYwWTMUsbVERoxr8wgcKo+SzNhuKMiRmaOAa+m+HYHMDPE28WUGA3NtIlGlC8xIrVCf4NAV5ThmNnL/CkhoBzndWhhFUwRdsaIK2CiV+sL/qopZx9V0yJqHIcWHYIm3DpLi+/Zc7og37hrSprCtH4kNc0hfpx4RbCjUL38+WR2gNu3VoouKKQv3M9dmzkwq9L+rNsnsuIlVdkR0PJFHdBsPGilWWjEBu37Y9hODk+Ueb15VrH2txSpT5TTknAMzHwzke+uZmARgwH3lD8HfzrQiyUfsrLbyIEztu428BLXNtFkhIZg1IPTr3CXO4CLm7N2JI60TxU9V5ce1lKayZxYUuSOBzG1e7fO2w3/rNVBLAdmjH6FUfewyNQKqNVfSluINglwpTBB1ZaupqZTSmoVgt5yrceshiUiwkk+OVEO8hMa4HUNwfSbjr1looXk4PWWn52JIT4=
